Repository nestjs/schematics, pull requests merged in 2018-05, with the labels that each got.

#62 fix() : service / provider module declaration
  src/utils/module.finder.ts
  test/service/factory.test.ts
  test/utils/module.finder.test.ts
Labels: bug, major

#63 enhancement() : use Jest as test framework
  package-lock.json
  package.json
  test/application/factory.test.ts
  test/class/factory.test.ts
  test/configuration/factory.test.ts
  test/controller/factory.test.ts
  test/decorator/factory.test.ts
  test/exception/factory.test.ts
  test/filter/factory.test.ts
  test/gateway/factory.test.ts
  test/guard/factory.test.ts
  test/interceptor/factory.test.ts
  test/jest-config.json
  test/middleware/factory.test.ts
  test/module/factory.test.ts
  test/pipe/factory.test.ts
  test/provider/factory.test.ts
  test/service/factory.test.ts
  test/utils/metadata.manager.test.ts
  test/utils/module-import.declarator.test.ts
  test/utils/module-metadata.declarator.test.ts
  test/utils/module.declarator.test.ts
  test/utils/module.finder.test.ts
  test/utils/name.parser.test.ts
  test/utils/path.solver.test.ts
  tsconfig.json
Labels: enhancement

#58 feature() : adjust templates to the best practices
  src/application/files/js/src/app.controller.js
  src/application/files/ts/src/app.module.ts
  src/filter/files/js/__name__.filter.js
  src/filter/files/ts/__name__.filter.ts
  src/gateway/files/js/__name__.gateway.js
  src/gateway/files/ts/__name__.gateway.ts
  src/guard/files/js/__name__.guard.js
  src/guard/files/ts/__name__.guard.ts
  src/interceptor/files/js/__name__.interceptor.js
  src/interceptor/files/ts/__name__.interceptor.ts
  src/middleware/files/js/__name__.middleware.js
  src/middleware/files/ts/__name__.middleware.ts
  src/pipe/files/ts/__name__.pipe.ts
  test/controller/factory.test.ts
  test/filter/factory.test.ts
  test/gateway/factory.test.ts
  test/guard/factory.test.ts
  test/interceptor/factory.test.ts
  test/middleware/factory.test.ts
  test/module/factory.test.ts
  test/pipe/factory.test.ts
  test/provider/factory.test.ts
  test/service/factory.test.ts
Labels: feature, major
